# Generated by Django 4.2 on 2024-03-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_initial_registration_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='initialregistration',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
