# Generated by Django 4.2 on 2024-03-26 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('is_scheduled', models.BooleanField(blank=True, default=False, null=True)),
                ('appointment_count', models.PositiveIntegerField()),
                ('booked_country', models.CharField(blank=True, default='Nepal', max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.UUIDField(unique=True)),
                ('applicant_name', models.CharField(max_length=300)),
                ('kyc_type', models.CharField(choices=[('Online', 'Online'), ('Recorded', 'Recorded')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('appointment_taken', 'appointment_taken'), ('appointment_booked', 'appointment_booked'), ('under_review', 'under_review'), ('approved', 'approved'), ('rejected', 'rejected'), ('closed', 'closed'), ('reverted', 'reverted')], default='appointment_taken', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_remarks', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('reschedule_count', models.PositiveIntegerField()),
                ('is_rebooked', models.BooleanField(default=False)),
                ('reverted_count', models.PositiveIntegerField(default=0)),
                ('close_remarks', models.TextField(blank=True, null=True)),
                ('reject_remarks', models.TextField(blank=True, null=True)),
                ('return_remarks', models.TextField(blank=True, null=True)),
                ('repair_remarks', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_recorded_to_live_converted', models.BooleanField(default=False)),
                ('recorded_to_live_conversion_reason', models.TextField(blank=True, null=True)),
                ('recorded_to_live_conversion_date', models.DateTimeField(blank=True, null=True)),
                ('is_live_to_recorded_converted', models.BooleanField(default=False)),
                ('live_to_recorded_conversion_date', models.DateTimeField(blank=True, null=True)),
                ('live_to_recorded_conversion_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('online_appointment', models.ManyToManyField(blank=True, to='kyc.appointmentmodel')),
                ('rejected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_by', to=settings.AUTH_USER_MODEL)),
                ('scheduled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_by', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYC',
                'ordering': ['-id'],
            },
        ),
    ]
